### PR TITLE
Example configs for 18.01 minikube and container building script

### PR DESCRIPTION
**Pull request by pcm32**
- Example configs tested for lifting a vanilla Galaxy setup (18.01) with helm. 
- Container building script to produce community images containers with the correct settings, configurable to look into different galaxy repos and ansible-galaxy-extras.

Will add documentation on how to use this on the readme.

### CODE REVIEW

**Comment by pcm32** [comment]
This addresses #10 .

**Comment by bgruening** [comment]
That is super cool!
Have you any idea how we can test this with some public CI system? Is there any CI system used to test k8s setups or that can run VMs like minicube?

**Comment by afgane** [comment]
We are pretty close to be being able to setup a k8s instance on demand from a vanilla Ubuntu machine so perhaps that can be used as the platform? It would also help make sure that setup is working as expected.

There's no documentation yet, but we use this playbook to bootstrap it all: https://github.com/CloudVE/ansible-cloudman2

**Comment by pcm32** [comment]
For testing, is possible to install minikube directly on a Travis VM these days.

**Comment by pcm32** [comment]
https://blog.travis-ci.com/2017-10-26-running-kubernetes-on-travis-ci-with-minikube

I have been meaning to put time on this for a while.

**Comment by bgruening** [comment]
Awesome!!!!

**Comment by nuwang** [comment]
Closes: https://github.com/galaxyproject/galaxy-kubernetes/issues/10

**Comment by pcm32** [comment]
Thanks for trying it @nuwang. Current difficulty is that you need to add a modified version of job_config.xml (as we do in the PhenoMeNal init container) where the runner is activated. I don't think that this can be done by just environment variable setting (as you need to actually add chunks of XML), so it would probably require a k8s specific job_config.xml that we could add into a k8s specific init container. That would be a first step.

Then, for truly running in anger in Kubernetes, you need to setup resource usage for tools, otherwise you can meltdown your cluster. We do this manually in PhenoMeNal (see [here](https://github.com/phnmnl/phenomenal-h2020/wiki/Setting-up-Galaxy-wrappers-on-PhenoMeNal-Galaxy-Container#tool-cpu-and-memory-usage-requests-and-limits)), but we might need a way that scales better for general Galaxy images (or just setting a default, but then demanding tools will suffer/fail).

**Comment by pcm32** [comment]
I wonder why you had to create your folder on minikube... I try it all the time with different prefixes and it always creates the folders on its own...

**Comment by nuwang** [comment]
I'm not really sure - I'm running minikube v0.27.0 on a Mac. The PVC was not being satisfied, so I manually created the folders and it was happy.

Enis and I were just thinking about the minikube setup. Is it ok if we switch to the dynamic provisioner instead of using a manually defined PV? That way, we won't need a special config for minikube. Also, is there a specific version of Kubernetes that you want to support? If the latest is ok, we were thinking that that 1.6+ or so would be good, since a lot of stuff like storage classes are out of beta since that version. In our case, we were planning on 1.10.0+

**Comment by pcm32** [comment]
But I don't think I'm supporting things earlier than 1.6 anymore in the helm charts.

**Comment by pcm32** [comment]
The error you describe seems to fit with https://github.com/kubernetes/minikube/issues/2256 which apparently was fixed on 0.25 (I'm on 0.25.2 I think, on macOS), maybe there was a regression on 0.27.0??

**Comment by pcm32** [comment]
I would suggest then that we make the minikube case the default, once advanced users try this locally, they might be more prone to spend money on a cloud provider to use it directly, will be willing to use more intricate settings and/or integrate it into their deployment method/cloud setup. For less advanced users, I don't even expect them to try direct deployments (but wrapper solutions like cloudman, phenomenal, etc). 

In my development experience with Galaxy-Minikube, is more useful to have the persistence storage working as you don't need to be uploading data each time to run tools or other configs, but it really doesn't matter I think, in the end you always end up using some additional setting that deviates from the default (like the init container that you will use for instance).

Should I make then the minikube setup the default? It would be nice to have a target Galaxy image to try this (so that tools work). Maybe an image with the tools used in usegalaxy.org? @bgruening will such a set of tools have all containers through bioconda/mulled? The only requirement would be that for all the tools that we add, automatic mapping to containers work. Where can I find the tool setup definition for those instances?

**Comment by pcm32** [comment]
> @bgruening Was there a specific reason for having galaxy-central in /export? If we leave galaxy-central within the container, and not in /export, would that make upgrades easier? (i.e. It looks like swapping containers is not enough, we also have to delete the galaxy-central folder manually from /export for a galaxy update to take effect - is that correct?)

I have been arguing the same with @bgruening. I think that we need to move out of the Galaxy web - init duality, and have people override tools and other settings through an additional container starting from the base one and we avoid all the time the /export copy process which can add some 3 to 4 minutes to deployment based on the writing speed of the shared file system.

What I do for the updates re /export is that I added functionality to force the copy of certain elements to /export on startup of the container (you specify these folders in the helm chart), but I agree with @nuwang that certain things should live in the container and only be linked from /export, to avoid this.

**Comment by pcm32** [comment]
I would suggest that the main separation of Galaxy containers in compose setup shouldn't be web - init, but web handler and jobs handlers, to truly scale on the amount of jobs that you can handle. This is probably not the best place to discuss that though.

**Comment by nuwang** [comment]
@pcm32 Just to make sure I understood what you meant by: "have people override tools and other settings through an additional container starting from the base one". I take it you mean that we build the base galaxy container, and then extend that Dockerfile to create a new container with the desired tools installed? If so, that sounds good to me.

I'm still not sure how the tool install database will be handled here, unless the database is sqlite. Is that what you're thinking?

**Comment by bgruening** [comment]
Hi,

the init-container needs to go away at some point, but there where technical limitation at the time we created them and there are still a few open Q. Happy to discuss this with all of you, whenever you have time.
One problem is, iff we want to move to handler-only containers we need to have a shared codebase, or we duplicate code across containers.

> I'm still not sure how the tool install database will be handled here, unless the database is sqlite. Is that what you're thinking?

Is the use-case the same as for the monolithic container? installing at first run will not work? If not the tool will be installed in the init-container and then moved into /export. At this time its fixed and you can not merge multiple flavors into one. But this was not possible before to my knowledge.

**Pull request merged**
